gitlab:
  image: gitlab/gitlab-ce:latest
  # container_name: gitlab
  ports:
    - "8443:443"
    - "8080:80"
    - "2222:22"
  volumes:
    - /Users/arungupta/tmp/gitlab/config:/etc/gitlab
    - /Users/arungupta/tmp/gitlab/logs:/var/log/gitlab
    - /Users/arungupta/tmp/gitlab/data:/var/opt/gitlab
  restart: always