id: mysql
kind: Service
apiVersion: v1beta3
metadata:
  name: mysql
  labels:
    name: mysql
    context: docker-k8s-lab
spec:
  ports:
    - port: 3306
  selector:
    name: mysql
  labels:
    name: mysql
