kind: ReplicationController
apiVersion: v1beta3
metadata:
  name: mysql-server
  labels:
    name: mysql-server
spec:
  replicas: 1
  selector:
    name: mysql-server
  template:
    metadata:
      labels:
        name: mysql-server
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_USER
              value: mysql
            - name: MYSQL_PASSWORD
              value: mysql
            - name: MYSQL_DATABASE
              value: sample
            - name: MYSQL_ROOT_PASSWORD
              value: supersecret
          ports:
            - containerPort: 3360
