kind: ReplicationController
apiVersion: v1beta3
metadata:
  name: wildfly
  labels:
    - name: wildfly
spec:
  replicas: 1
  selector:
    name: wildfly-server
  template:
    metadata:
      labels:
        - name: wildfly-server
      spec:
        containers:
          - name: javaee7-app
            image: arungupta/wildfly-mysql-javaee7:knetes
            ports:
              - containerPort: 8080