dockerregistry:
  image: registry:2.0
  volumes:
    - /registry:/tmp/registry-dev
  ports: 
    - "5000:5000"
httpserver:
  build: dockerfiles/lab-httpd-server/
  ports: 
    - "8082:80"
nexusdata:
  image: sonatype/nexus:oss
  command: echo "data-only container for Nexus"
nexus:
  image: sonatype/nexus:oss
  ports:
    - "8081:8081"
  volumes_from: 
    - nexusdata
postgresqlgitlab:
  image: sameersbn/postgresql:9.4
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
  volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql
redisgitlab:
  image: sameersbn/redis:latest
  volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis
gitlab:
  image: sameersbn/gitlab:7.10.4
  links:
    - redisgitlab:redisio
    - postgresqlgitlab:postgresql
  ports:
    - "10080:80"
    - "10022:22"
  environment:
    - GITLAB_HOST=localhost
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - GITLAB_ROOT_PASSWORD=dockeradmin
    - GITLAB_USERNAME_CHANGE=false
    - GITLAB_CREATE_GROUP=false
    - GITLAB_PROJECTS_ISSUES=false
    - GITLAB_PROJECTS_MERGE_REQUESTS=false
    - GITLAB_PROJECTS_WIKI=false
    - GITLAB_BACKUPS=disable
  volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data
