mycouchbase:
  container_name: "db"
  image: arungupta/couchbase
  ports:
    - 8091:8091
    - 8092:8092 
    - 8093:8093 
    - 11210:11210
mywildfly:
  image: arungupta/wildfly-couchbase-javaee7
  environment:
    - COUCHBASE_URI=db
  ports:
    - 8080:8080

